name: liquidhaskell-tutorial
version: '0.2.0.0'
synopsis: Source for "Programming with Refinement Types"
category: Web
author: Ranjit Jhala
maintainer: jhala@cs.ucsd.edu
copyright: Ranjit Jhala
license: MIT
homepage: https://github.com/ucsd-progsys/liquidhaskell-tutorial

extra-source-files:
- README.md

dependencies:
- base
- template
- containers
- text
- bytestring
- directory
- pandoc-types
- pandoc
- filepath
- unix

executables:
  filters-toc:
    main: filters/Toc.hs
    ghc-options: -main-is Toc -threaded
  filters-links:
    main: filters/Links.hs
    ghc-options: -main-is Links -threaded
  filters-latex:
    main: filters/Latex.hs
    ghc-options: -main-is Latex -threaded
  filters-html:
    main: filters/Html.hs
    ghc-options: -main-is Html -threaded
  filters-figures:
    main: filters/Figures.hs
    ghc-options: -main-is Figures -threaded
  filters-codeblock:
    main: filters/Codeblock.hs
    ghc-options: -main-is Codeblock -threaded
  toplevel:
    main: Main.hs
